<a href="https://colab.research.google.com/github/aman685892/Data-Science-Practice/blob/main/Numpy_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [259]:
import numpy as np
arr1=np.array([1,2,3,4])
print(arr1)

[1 2 3 4]
[1 2 3 4]


In [260]:
print(type(arr1))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [261]:
print(arr1.shape)

(4,)
(4,)


In [262]:
arr2=np.array([1,2,3,4,5])
print(arr2.reshape(1,5))

[[1 2 3 4 5]]
[[1 2 3 4 5]]


In [263]:
print(arr2.shape)

(5,)
(5,)


In [264]:
arr3=np.array([[1,2,3,4,5]])
print(arr3.shape)

(1, 5)
(1, 5)


In [267]:
arr4=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr4)
print(arr4.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [268]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [269]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [270]:
## Identitiy matrix
np.eye(3,) ## all diagonal elements will be zero

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [271]:
## Attributes of Numpy array
arr=np.array([[1,2,3],[4,5,6]])
print("Array:",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size(Number of elements):",arr.size)
print("Data Type:",arr.dtype)
print("Item size(in bytes):",arr.itemsize)

Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size(Number of elements): 6
Data Type: int64
Item size(in bytes): 8


In [272]:
## Numoy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
## Elememnt wise addition
print("Addition",arr1+arr2)
##Element wise subtraction
print("Subtraction:",arr1-arr2)
##Element wise multiolication
print("Multiplication",arr1*arr2)
 ##Elemnet wise division
print("Division",arr1/arr2)

Addition [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]


In [273]:
## Univrsal fuction
arr5=np.array([2,3,5,6,7])
## square root
print(np.sqrt(arr5))
##Exponential function
print(np.exp(arr5))
## sine function
print(np.sin(arr5))
##Cosine function
print(np.cos(arr5))
## natural log
print(np.log(arr5))

[1.41421356 1.73205081 2.23606798 2.44948974 2.64575131]
[   7.3890561    20.08553692  148.4131591   403.42879349 1096.63315843]
[ 0.90929743  0.14112001 -0.95892427 -0.2794155   0.6569866 ]
[-0.41614684 -0.9899925   0.28366219  0.96017029  0.75390225]
[0.69314718 1.09861229 1.60943791 1.79175947 1.94591015]


In [274]:
## Array indexing and slicing using numpy
arr7=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr7)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [275]:
print(arr7[0])

[1 2 3 4]


In [276]:
print(arr7[0][0])

1


In [277]:
print(arr7[1:2:])

[[5 6 7 8]]


In [278]:
print(arr7[1:,2:])

[[ 7  8]
 [11 12]]


In [279]:
print(arr7[0:2,2:])

[[3 4]
 [7 8]]


In [280]:
## Modify the array elemets
arr7[0][0]=100
print(arr7)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [281]:
arr7[1:]=9
print(arr7)

[[100   2   3   4]
 [  9   9   9   9]
 [  9   9   9   9]]


In [282]:
## Statistical concepts-- Normalization
## to have  a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])
## calculate the mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)
# Normalize the data
Normalized_data=(data-mean)/std_dev
print(Normalized_data)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [283]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
## Mean
print(np.mean(data))
print(np.median(data))
print(np.var(data))
print(np.std(data))

5.5
5.5
8.25
2.8722813232690143


In [256]:
## Logical operation
data1=np.array([1,2,3,4,5,6,7,8,9,10])
data1>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [257]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [258]:
data1[(data>=5 & (data<=8))]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])