<a href="https://colab.research.google.com/github/aman685892/Data-Science-Practice/blob/main/Numpy_In_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [129]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [130]:
print(type(arr1))

<class 'numpy.ndarray'>


In [131]:
## creating another array using numpy
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 columns


array([[1, 2, 3, 4, 5]])

In [132]:
## 2d arrays
arr3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr3.shape)

(2, 5)


In [133]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [134]:
## inbuilt functions in numpy
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [135]:
## identiity matrix
np.eye(3) # all the diagonal elememnts must be 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [136]:
arr=np.array([[1,2,3],[4,5,6]])
print("Array:",arr)
print("Array size:",arr.size)
print("Array shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("data type:",arr.dtype)
print("Item size in bytes:",arr.itemsize)

Array: [[1 2 3]
 [4 5 6]]
Array size: 6
Array shape: (2, 3)
Number of dimensions: 2
data type: int64
Item size in bytes: 8


In [137]:
## Numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
## Element wise addition
print("Addition:",arr1+arr2)
## Element wise substraction
print("Substraction:",arr1-arr2)
## Element wise multiplication
print("Multiplication:",arr1*arr2)
## Elemnet wise Division
print("Division:",arr1/arr2)


Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [138]:
## Universal functions
arr4=np.array([1,2,3,4,5])
print(np.sqrt(arr4))# Square root
print(np.sin(arr4))# Sine values (radians me)
print(np.log(arr4)) # Natural log (base e)

[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [139]:
arr7=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array is:",arr7)

Array is: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [140]:
## Indexing and slicing in array using numpy
print(arr7[0][0])

1


In [141]:
print(arr7[1:,2:])

[[ 7  8]
 [11 12]]


In [142]:
print(arr7[1:,1:3])

[[ 6  7]
 [10 11]]


In [143]:
## modify the array elements
arr7[0,0]=100
arr7

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [144]:
arr7[1:]=100
print(arr7)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [145]:
## Statistical concepts -- Normalization
## to have  a mean of 0 and std of 1
data=np.array([1,2,3,4,5])
# calculate the mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)
print(mean)
print(std_dev)
## Normalized the data
normalized_data=(data-mean)/std_dev
print(normalized_data)
## variance
variance=np.var(data)
print(variance)

3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
2.0


In [146]:
## Logical operation
data=np.array([1,2,3,4,5])
(data>2)

array([False, False,  True,  True,  True])

In [147]:
data[data>2]

array([3, 4, 5])

In [148]:
data[(data>2)&(data<5)]

array([3, 4])